### ISSUE TITLE
fmt dependency missing

### ISSUE THREAD

**Issue by BugInACode** [longmakesstuff/FFT-Power-Spectrum#3]
When building I would get

    home/$USER/FFT-Power-Spectrum/include/utils/Utils.h:4:10: fatal error: fmt/core.h: No such file or directory

    4 | #include <fmt/core.h>

      |          ^~~~~~~~~~~~

    compilation terminated.

seems like `fmt` is a third party library and can be added [as such](https://stackoverflow.com/questions/66531225/cmake-add-fmt-library)

**Comment by longmakesstuff** [comment]
@BugInACode thanks. I don't know how FMT gets into my code :D deleted the include anyway.
